image: node:20
  - build
  - deploy

cache:
  key:
    files:
      - package-lock.json
  paths:

    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "dev"

pages:
  stage: deploy
  needs: ["build"]
  script:
    - mkdir -p public
    - cp -r dist/. public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "dev"
