-- Généré automatiquement par scripts/generate-skill-definitions-seed.js
-- à partir de src/data/branches.js — NE PAS éditer ce fichier à la main,
-- relancer le script après toute modification de branches.js.

INSERT INTO skill_definitions (skill_id, xp_cost, requires) VALUES
  ('ecca', 25, '{"root"}'),
  ('gitlab', 50, '{"ecca"}'),
  ('rhcsa', 50, '{"ecca"}'),
  ('rhce', 75, '{"rhcsa"}'),
  ('h5a', 120, '{"rhce"}'),
  ('h5b', 130, '{"rhce"}'),
  ('h6', 180, '{"h5a","h5b"}'),
  ('sb_hero', 220, '{"h6"}'),
  ('sb_hero_2', 220, '{"h6"}'),
  ('sb_hero_3', 220, '{"h6"}'),
  ('boss_hero', 350, '{"sb_hero","sb_hero_2","sb_hero_3"}'),
  ('ejpt', 25, '{"root"}'),
  ('ecppt', 50, '{"ejpt"}'),
  ('ewpt', 75, '{"ecppt"}'),
  ('adrts', 75, '{"ecppt"}'),
  ('crtp', 100, '{"adrts"}'),
  ('oswp', 80, '{"adrts"}'),
  ('cpts', 100, '{"adrts"}'),
  ('emap', 80, '{"adrts"}'),
  ('rscp', 120, '{"cpts"}'),
  ('crte', 125, '{"crtp"}'),
  ('crtm', 150, '{"crte"}'),
  ('oscp', 130, '{"crtp"}'),
  ('oslf', 150, '{"oscp"}'),
  ('oswe', 140, '{"crtp"}'),
  ('osce', 180, '{"oswe"}'),
  ('sb_warrior', 220, '{"crtm"}'),
  ('sb_warrior_2', 220, '{"osce"}'),
  ('sb_warrior_3', 220, '{"oslf"}'),
  ('final_boss', 350, '{"sb_warrior","sb_warrior_2","sb_warrior_3"}'),
  ('ejca', 25, '{"root"}'),
  ('cdsa', 60, '{"ejca"}'),
  ('d3a', 75, '{"cdsa"}'),
  ('d3b', 75, '{"cdsa"}'),
  ('d4a', 100, '{"d3a"}'),
  ('d4b', 100, '{"d3b"}'),
  ('d5a', 130, '{"d4a"}'),
  ('d5b', 140, '{"d4b"}'),
  ('d6', 180, '{"d5a","d5b"}'),
  ('sb_primitive', 220, '{"d6"}'),
  ('sb_prim_2', 220, '{"d6"}'),
  ('sb_prim_3', 220, '{"d6"}'),
  ('boss_primitive', 350, '{"sb_primitive","sb_prim_2","sb_prim_3"}')
ON CONFLICT (skill_id) DO UPDATE
  SET xp_cost = EXCLUDED.xp_cost,
      requires = EXCLUDED.requires;
