CREATE TABLE ai_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  theme TEXT NOT NULL,              -- 'culture', 'rpg', 'sport'...
  mode TEXT NOT NULL,               -- 'coop_meute', 'party_salon', 'raid_boss'
  difficulty TEXT NOT NULL,         -- 'rookie', 'hunter', 'monarque'
  question TEXT NOT NULL,
  options JSONB NOT NULL,           -- ["...", "...", "...", "..."]
  answer TEXT NOT NULL,
  explanation TEXT,
  status TEXT DEFAULT 'pending',    -- 'pending' | 'approved' | 'rejected'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE ai_questions ENABLE ROW LEVEL SECURITY;

-- Lecture publique uniquement des questions approuvées
CREATE POLICY "Public read approved" ON ai_questions
  FOR SELECT USING (status = 'approved');
