-- Table des questions générées par l'IA (Gemini), en attente de validation
CREATE TABLE ai_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  theme TEXT NOT NULL,              -- 'culture', 'rpg', 'sport', 'cinema', 'animaux', 'musique'
  mode TEXT NOT NULL,               -- 'coop_meute', 'party_salon', 'raid_boss', 'bluff_royal'
  difficulty TEXT NOT NULL,         -- 'rookie', 'hunter', 'monarque'
  type TEXT NOT NULL DEFAULT 'mcq' CHECK (type IN ('mcq', 'bluff')),
  question TEXT NOT NULL,
  options JSONB NOT NULL DEFAULT '[]'::jsonb, -- vide pour le type 'bluff'
  answer TEXT NOT NULL,
  explanation TEXT,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_by UUID REFERENCES auth.users ON DELETE SET NULL,
  reviewed_by UUID REFERENCES auth.users ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  reviewed_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_ai_questions_status ON ai_questions(status);
CREATE INDEX idx_ai_questions_theme ON ai_questions(theme);
CREATE INDEX idx_ai_questions_type ON ai_questions(type);

ALTER TABLE ai_questions ENABLE ROW LEVEL SECURITY;

-- Tout le monde (même anonyme) peut lire les questions déjà approuvées : ce sont
-- celles utilisées en jeu.
CREATE POLICY "Public read approved questions" ON ai_questions
  FOR SELECT USING (status = 'approved');

-- Seuls les admins (profiles.role = 'admin') peuvent voir les questions en attente
-- ou rejetées, pour la page de modération.
CREATE POLICY "Admins read all questions" ON ai_questions
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

-- Seuls les admins peuvent changer le statut (approuver / rejeter)
CREATE POLICY "Admins update questions" ON ai_questions
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

-- Seuls les admins peuvent insérer des questions directement (Utile pour l'admin panel en local/fallback)
CREATE POLICY "Admins insert questions" ON ai_questions
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

-- L'insertion se fait principalement via l'Edge Function (service_role key),
-- qui bypass RLS par nature -- donc pas de policy INSERT pour les rôles publics.

