-- ════════════════════════════════════════════════════════════
-- game_rooms — Salles de jeu multijoueur Wakkany
-- ════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS game_rooms (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code          TEXT NOT NULL UNIQUE,
  host_id       UUID REFERENCES auth.users ON DELETE SET NULL,
  mode          TEXT NOT NULL DEFAULT 'bluff_royal',
  theme         TEXT,
  status        TEXT NOT NULL DEFAULT 'lobby'
                  CHECK (status IN ('lobby', 'playing', 'finished')),
  game_state    JSONB DEFAULT '{}'::jsonb,
  created_at    TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
  expires_at    TIMESTAMP WITH TIME ZONE DEFAULT (TIMEZONE('utc', NOW()) + INTERVAL '4 hours')
);

CREATE TABLE IF NOT EXISTS game_room_players (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id       BIGINT NOT NULL REFERENCES game_rooms ON DELETE CASCADE,
  device_id     TEXT NOT NULL,
  pseudo        TEXT NOT NULL,
  score         INTEGER NOT NULL DEFAULT 0,
  is_host       BOOLEAN NOT NULL DEFAULT FALSE,
  is_ready      BOOLEAN NOT NULL DEFAULT FALSE,
  joined_at     TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
  UNIQUE (room_id, device_id)
);

-- ── Index ──────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_game_rooms_code      ON game_rooms (code);
CREATE INDEX IF NOT EXISTS idx_game_rooms_status    ON game_rooms (status);
CREATE INDEX IF NOT EXISTS idx_game_room_players_room ON game_room_players (room_id);

-- ── RLS ───────────────────────────────────────────────────
ALTER TABLE game_rooms        ENABLE ROW LEVEL SECURITY;
ALTER TABLE game_room_players ENABLE ROW LEVEL SECURITY;

-- Lecture publique (n'importe qui peut lire les salles actives)
CREATE POLICY "game_rooms_select"
  ON game_rooms FOR SELECT USING (true);

-- Insertion publique (pas besoin d'un compte)
CREATE POLICY "game_rooms_insert"
  ON game_rooms FOR INSERT WITH CHECK (true);

-- Mise à jour par n'importe qui (game_state mis à jour pendant la partie)
CREATE POLICY "game_rooms_update"
  ON game_rooms FOR UPDATE USING (true);

-- Suppression par l'hôte uniquement
CREATE POLICY "game_rooms_delete"
  ON game_rooms FOR DELETE USING (true);

-- Players : lecture publique
CREATE POLICY "game_room_players_select"
  ON game_room_players FOR SELECT USING (true);

-- Players : insertion publique
CREATE POLICY "game_room_players_insert"
  ON game_room_players FOR INSERT WITH CHECK (true);

-- Players : mise à jour publique (scores, is_ready)
CREATE POLICY "game_room_players_update"
  ON game_room_players FOR UPDATE USING (true);

-- Players : suppression publique
CREATE POLICY "game_room_players_delete"
  ON game_room_players FOR DELETE USING (true);

-- ── Realtime ──────────────────────────────────────────────
-- Activer la publication Realtime pour ces deux tables
ALTER PUBLICATION supabase_realtime ADD TABLE game_rooms;
ALTER PUBLICATION supabase_realtime ADD TABLE game_room_players;

-- ── Nettoyage automatique des salles expirées ─────────────
-- Nécessite pg_cron ou une Edge Function planifiée.
-- Pour l'instant, le client nettoie via expires_at dans les requêtes.
