-- Schéma SQL pour la Plateforme Wakkany

-- 1. Table des Profils (utilisateurs)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  username TEXT UNIQUE,
  role TEXT DEFAULT 'user', -- 'admin' or 'user'
  xp INTEGER DEFAULT 0,
  level INTEGER DEFAULT 1,
  avatar_state JSONB DEFAULT '{}',
  dominant_branch TEXT DEFAULT 'Novice',
  school TEXT DEFAULT 'Nomade',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Table des Compétences Débloquées
CREATE TABLE unlocked_skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  skill_id TEXT NOT NULL,
  unlocked_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  UNIQUE(user_id, skill_id)
);

-- 3. Table des Quêtes Complétées
CREATE TABLE completed_quests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  quest_id TEXT NOT NULL,
  completed_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  UNIQUE(user_id, quest_id)
);

-- 4. Table des Clans
CREATE TABLE clans (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  icon TEXT DEFAULT 'lucide:shield',
  color TEXT DEFAULT '#c28e3a',
  owner_id UUID REFERENCES auth.users NOT NULL,
  prestige_xp INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Ajout de la liaison clan dans les profils
ALTER TABLE profiles ADD COLUMN clan_id UUID REFERENCES clans(id) ON DELETE SET NULL;

-- 5. Sécurité (RLS - Row Level Security)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE unlocked_skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE completed_quests ENABLE ROW LEVEL SECURITY;
ALTER TABLE clans ENABLE ROW LEVEL SECURITY;

-- Politiques de lecture (Tout le monde peut voir les profils et les clans pour le leaderboard)
CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR SELECT USING (true);
CREATE POLICY "Public clans are viewable by everyone" ON clans FOR SELECT USING (true);

-- Politiques d'écriture (Seul l'utilisateur peut modifier ses propres données)
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Users can insert own skills" ON unlocked_skills FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can insert own quests" ON completed_quests FOR INSERT WITH CHECK (auth.uid() = user_id);
